# -*- coding: utf-8 -*-
"""Aula22-03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J5I9VNUem1yfCmBm_IPuQiOWZXSX-527

**BIBLIOTECAS -->**
É UM CONJUNTO DE FUNÇÕES E CÓDIGOS PRONTOS QUE FACILITAM O DESENVOLVIMENTO DOS PROGRAMAS. USAMOS O COMANDO **IMPORT** PARA IMPORTÁ-LAS.
"""

5*3

import math

math.sqrt(16) #retorna a raiz quadrada de 16

math.pow(5,2) #retorna o primeiro número elevado pelo segundo número

math.factorial(5)

import random

random.randint(1,100) #gera um número aleatório entre 1 e 100

random.choice([14,20,35,112,77])#ele escolhe entre os números declarados entre chaves

import datetime

datetime.date.today() #retorna a data atual

datetime.date.today().day #retorna a data atual (dia)

datetime.date.today().month #retorna a data atual (mês)

datetime.date.today().year #retorna a data atual (ano)

import time #biblioteca de temporizador

for contador in range(5):
  print('Conectando...')
  time.sleep(1)

"""LISTAS"""

lista = [1,2,3,4,5] #cria uma lista com valores é diferente de vetor

lista

print(lista)

type(lista) #retorna o tipo da variável

lista[0] #retorna a quantidade de elementos na lista, como existe o 0 que é um elemento

lista[4]

#INSERINDO ELEMENTOS NA LISTA
 
lista

lista.append(6) #Insere um elemento no final da lista

lista

lista[1] = 100 #sobrepõe o elemento do índice informado. Colocamos o 100 no lugar do 2

lista

del lista[1] #apaga o elemento da lista da posição informada. Apagamos o 100, NÃO APAGA O ESPAÇO DA MEMÓRIA

lista

lista.insert(1,2) #INSERE O VALOR NA POSIÇÃO INFORMADA. PRIMEIRO É A POSIÇÃO E DEPOIS O VALOR

lista

lista.remove(4)#REMOVE O ELEMÊNTO DO PARÂMETRO. APAGA O ESPAÇO DA MEMÓRIA

lista

lista.pop()#Senão informar o parâmetro ele elimina sempre o último elemento da lista

lista

lista.pop(2)#Informando o parâmetro, ele remove o índice informado

lista

numeros = list()#CRIA UMA LISTA VAZIA

numeros

type(numeros)

numeros.append(10)

numeros

numeros.append(26)

numeros

#CRIANDO UMA LISTA COM RANGE

valores = list(range(1,10))#O último número é exclusivo, quero do 1 até o antecessor do 10

valores

valores[-1] #retorna o último valor da lista

print(valores)
valores[:3]#Determinação da margem que deverá ser apresentada

print(valores)
valores[3:]#Determinação da margem que deverá ser apresentada

print(valores)
valores[:]#Determinação da margem que deverá ser apresentada

lista1 = [33,5,91,14,8,3]

lista1.sort()#COLOCA A LISTA EM ORDEM CRESCENTE

lista1

lista1.sort(reverse=True)#COLOCA A LISTA EM ORDEM INVERSA != DECRESCENTE

lista1

min(lista1)#O VALOR MAIS BAIXO DA LISTA

max(lista1)#O VALOR MAIS ALTO DA LISTA

sum(lista1)#A SOMA DE TODOS OS VALORES DA LISTA

len(lista1)#A QUANTIDADE DE VALORES NA LISTA

14 in lista1 #O VALOR 14 ESTÁ NA LISTA? VERDADE!

72 in lista1 #O VALOR 72 ESTÁ NA LISTA? FALSO

if 14 in lista1: #Caso o valor esteja na lista ele remove e se não estiver ele imprime a frase 
  lista1.remove(14)
else:
  print('Não achei o valor solicitado na lista')

for i in lista1:
  print(i)

for i in lista1:
  print(i, end=' ') #imprime tudo na mesma linha

for i in enumerate(lista1):#retora a lista, o valor e a posição no índice
  print(i)

#INSERINDO OS VALORES DA LISTA PELO TECLADO

valores1 = [] #Outra opção é usar valores1 = list()

for i in range(5):
  valores1.append(int(input('Digite um valor: ')))

  print(valores1)

#CRIANDO UMA LISTA COM STRING

estados = ['SÃO PAULO', 'BAHIA', 'RIO DE JANEIRO', 'MINAS GERAIS']

estados

print('O estado sorteado foi:', random.choice(estados))

lista.clear()#apaga a lista

lista

a = [1,2,3]
b = [4,5,6]

print(a)
print(b)

a.extend(b) #Juntando as duas listas

print(a)



"""**EXERCÍCIO**
**1)** Faça um programa que leia 5 valores do teclado e armazene em uma lista e em seguida moste:
**a)** O maior valor
**b)** o menor valor
**c)** o número de elementos da lista
**d)** o último valor da lista
"""

val = []

for i in range(5):
  val.append(int(input('Por favor, digite um valor: ')))

val

print('O maior valor digitado é: ', max(val))
print('O menor valor digitado é: ', min(val))
print('A quantidade de elementos digitados foi: ', len(val))
print('O último valor digitado é ', val.pop())

"""**EXERCÍCIO**
**02)** Faça um programa para sortear um nome de uma lista de nomes
"""

Sorte = ['KENDAL', 'KATHERINE', 'LUÍS', 'FELLIPE']
print('O nome sorteado foi: ', random.choice(Sorte))

"""**EXERCÍCIO**
**03)**
Faça um programa que leia o nome e 3 notas de um aluno. As notas deverão ser armazenadas em uma lista. No final, o programa deverá mostrar a média do aluno
"""

nome = input('Digite o nome do(a) aluno(a)')
notas = []

for i in range(3):
  notas.append(int(input('Digite o valor da nota: ')))

media = ((notas[0] + notas[1] + notas[2]) / 3)

print(f'O(a) aluno(a) {nome}, tem como média: {media}')

"""EXERCÍCIO 04)
Crie uma lista com 20 números inteiros. Em seguida armazene os números pares em uma lista chamada PAR e os números ímpares em ula lista ÍMPAR. Imprima as listas PAR e ÍMPAR

"""

numeros = list(range(1,21))
pares=[]
impares=[]

impares = [ el for el in numeros if el % 2 != 0 ]
pares = [ el for el in numeros if el % 2 == 0 ]


print(impares)
print(pares)

"""EXERCÍCIO 05) Faça um programa que procure um determinado valor em uma lista, se encontrar, mostre o valor """

x = int(input('DIGITE UM NÚMERO: '))

if x in numeros: 
  print(f'O número "{x}" está na lista')
else:
  print(f'O número "{x}" não está na lista')

